# Jupyter Book Configuration
# Learn more at https://jupyterbook.org/customize/config.html

title: Python Training Materials
author: Matt Deakyne
copyright: "2025"
logo: ""

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 100
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: python-training.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/mdeakyne/python_teaching
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  baseurl: https://mdeakyne.github.io/python_teaching/

# Sphinx configuration
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      repository_url: https://github.com/mdeakyne/python_teaching
      use_repository_button: true
      use_issues_button: true
      path_to_docs: docs
      repository_branch: main
    language: en

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# Exclude patterns
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
